[build-system]
requires = ["hatchling>=1.24.2"]
build-backend = "hatchling.build"

[project]
name = "fhops"
version = "0.1.0"
description = "Forest Harvesting Operations Planning System"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [{name="UBC FRESH Lab"}]
dependencies = [
  "typer>=0.9.0",
  "rich>=13.7.0",
  "pydantic>=2.6.0",
  "pandas>=2.2.0",
  "numpy>=1.26.0",
  "pyomo>=6.7.0",
  "highspy>=1.7.0",
  "pyarrow>=15.0.0"
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0.0",
  "pytest-cov>=5.0.0",
  "ruff>=0.4.0",
  "black>=24.0.0",
  "mypy>=1.10.0",
  "pre-commit>=3.7.0"
]
geo = [
  "geopandas>=0.14.0"
]

[project.scripts]
fhops = "fhops.cli.main:app"

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E","F","I","W","UP"]
ignore = ["E501"]
target-version = "py311"

[tool.mypy]
python_version = "3.11"
strict = false
warn_unused_ignores = true
exclude = ["examples"]

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["src"]
